# Create/Clean and Format the Product and Service Categories Dataset for Graphs

# Clear environment
# rm(list = ls())

options(scipen = 20, digits = 2)

library(dplyr)
library(Hmisc)
library(plyr)
library(tidyr)
library(stats)

# Create Working Directory
local_dir <- "C:\\Users\\Desktop\\"
setwd(local_dir)

# Extend memory accessible for loops/calculations
memory.limit(size = 56000)

# Load Each Year of Contracts Data from Script 2
contracts18 <- readRDS(file = "Part_I_Data\\Script2-formattedcontracts2018.RData")
contracts17 <- readRDS(file = "Part_I_Data\\Script2-formattedcontracts2017.RData")
contracts16 <- readRDS(file = "Part_I_Data\\Script2-formattedcontracts2016.RData")
contracts15 <- readRDS(file = "Part_I_Data\\Script2-formattedcontracts2015.RData")
contracts14 <- readRDS(file = "Part_I_Data\\Script2-formattedcontracts2014.RData")
contracts13 <- readRDS(file = "Part_I_Data\\Script2-formattedcontracts2013.RData")
contracts12 <- readRDS(file = "Part_I_Data\\Script2-formattedcontracts2012.RData")
contracts11 <- readRDS(file = "Part_I_Data\\Script2-formattedcontracts2011.RData")
contracts10 <- readRDS(file = "Part_I_Data\\Script2-formattedcontracts2010.RData")
contracts09 <- readRDS(file = "Part_I_Data\\Script2-formattedcontracts2009.RData")
contracts08 <- readRDS(file = "Part_I_Data\\Script2-formattedcontracts2008.RData")
contracts07 <- readRDS(file = "Part_I_Data\\Script2-formattedcontracts2007.RData")
 
#############
# Create parent naisc and psc code totals separating first two characters of each psc code
psclist <- lapply(
  list(contracts18, contracts17, contracts16, contracts15, contracts14, contracts13,
       contracts12, contracts11, contracts10, contracts09, contracts08, contracts07), 
  function(df) {
    df2 <- separate(df, product_or_service_code, c("psc_cat", "psccode_adden"), sep = 2, remove = FALSE)
    return(df2)
  }
)

# Unnest the data from the list generated by the loop
contracts18_p <- unnest_(psclist[[1]])
contracts17_p <- unnest_(psclist[[2]])
contracts16_p <- unnest_(psclist[[3]])
contracts15_p <- unnest_(psclist[[4]])
contracts14_p <- unnest_(psclist[[5]])
contracts13_p <- unnest_(psclist[[6]])
contracts12_p <- unnest_(psclist[[7]])
contracts11_p <- unnest_(psclist[[8]])
contracts10_p <- unnest_(psclist[[9]])
contracts09_p <- unnest_(psclist[[10]])
contracts08_p <- unnest_(psclist[[11]])
contracts07_p <- unnest_(psclist[[12]])

# Remove the list created 
rm(psclist)
# Remove the original datasets loaded into environment
rm(contracts18, contracts17, contracts16, contracts15, contracts14, contracts13,
   contracts12, contracts11, contracts10, contracts09, contracts08, contracts07)

# Using the datasets with parent psc code, create a weekly aggregate of contract spending
psclist <- lapply(
  list(contracts18_p, contracts17_p, contracts16_p, contracts15_p, contracts14_p, contracts13_p,
       contracts12_p, contracts11_p, contracts10_p, contracts09_p, contracts08_p, contracts07_p), 
  function(df) {
    df2 <-  df %>% group_by(yrweek, psc_cat, product_or_service_code) %>%
      dplyr::summarise(contractcount = n(),
                       contractdollars = sum(dollarsobligated, na.rm = TRUE)) 
    return(df2)
  }
)

# Remove the contracts dataframes
rm(contracts18_p, contracts17_p, contracts16_p, contracts15_p, contracts14_p, contracts13_p,
   contracts12_p, contracts11_p, contracts10_p, contracts09_p, contracts08_p, contracts07_p)

# Unnest aggregated weekly contract spending by psc category datasets from list created by the loop
contracts18_psc <- unnest_(psclist[[1]])
contracts17_psc <- unnest_(psclist[[2]])
contracts16_psc <- unnest_(psclist[[3]])
contracts15_psc <- unnest_(psclist[[4]])
contracts14_psc <- unnest_(psclist[[5]])
contracts13_psc <- unnest_(psclist[[6]])
contracts12_psc <- unnest_(psclist[[7]])
contracts11_psc <- unnest_(psclist[[8]])
contracts10_psc <- unnest_(psclist[[9]])
contracts09_psc <- unnest_(psclist[[10]])
contracts08_psc <- unnest_(psclist[[11]])
contracts07_psc <- unnest_(psclist[[12]])

# Bind each year of Psc Weekly Contract Spending Data into One large Data frame for 2007-2018
pscdata <- rbind(contracts18_psc, contracts17_psc, contracts16_psc, contracts15_psc, contracts14_psc, 
                 contracts13_psc, contracts12_psc, contracts11_psc, contracts10_psc, 
                 contracts09_psc, contracts08_psc, contracts07_psc)

# Clean descriptions or codes with missing value if empty or unreported (missing/unknown = 9999)
pscdata$psc_cat[(pscdata$psc_cat == "" | pscdata$psc_cat == " " | 
                   is.na(pscdata$psc_cat))] <- 99
pscdata$product_or_service_code[(pscdata$product_or_service_code == "" | 
                                   pscdata$product_or_service_code == " " | 
                                   is.na(pscdata$product_or_service_code)  | pscdata$psc_cat == 99)] <- 9999

# Remove list created by loop
rm(psclist)

# Aggregate the ten year dataset at teh weekly level to eliminate duplicates due to NAs/Missing/dropped psccodes
pscdata <-  pscdata %>% group_by(yrweek, psc_cat, product_or_service_code) %>%
  dplyr::summarise(contractcount = sum(contractcount),
                   contractdollars = sum(contractdollars)) 

# Load timeindex created in script #3
timeindex <- readRDS(file = "Part_I_Data\\Script3-DateIndexbyYearWeek.RData")

# Merge ten year psc dataset with timeindex to match the correct year/week with the fiscal year
pscdata <- merge(pscdata, timeindex, by = "yrweek")
pscdata <- pscdata[!(names(pscdata) %in% c("yrweek"))]

# Import GSA/Level1 PSC Category Index
newcodes <- readRDS(file = "Part_II_Data\\NewPSCCodeIndex.RData")

# Bind pscdata to the psc index created using the detailed (4digit) code
pscdata <- merge(pscdata, newcodes, by.x = "product_or_service_code", by.y = "psCode", all.x = TRUE)

# Remove duplicated/unneeded columns
pscdata <- pscdata[names(pscdata) %in% c("date", "Model.Categorization","contractdollars", 
                                          "product_or_service_code", "fiscalYear")]

# Save the aggregated dataset, Contract Dollars by PSC Parent Categories
saveRDS(pscdata, file = "Part_I_Data\\Script5-PSCWeeklyTotals_CodeCategorization.RData")

# Aggregate contract dollars by the Parent PSC Categories Created "Model.Categorization"
pscdata_cat <- pscdata %>% group_by(date, Model.Categorization) %>%
  dplyr::summarise(contractdollars = sum(contractdollars, na.rm = TRUE))

# Rename columns for visualization code
colnames(pscdata_cat) <- c("date", "lineData", "val")

# Save the aggregated dataset, Contract Dollars by PSC Parent Categories
saveRDS(pscdata_cat, file = "Part_I_Data\\Script5-PSCWeeklyTotals_withCategorization.RData")

# Calculate PSC Category Variances
varianceTable <- pscdata_cat %>% group_by(lineData) %>% 
  dplyr::summarise(variance = var(val, use = "all.obs"), 
                   mean = mean(val), 
                   totalgrp = sum(val))
# Save/Export variance table
write.csv(varianceTable, file = "Output\\VarianceTable_PSCData_Totals_RawData.csv", row.names = FALSE)

rm(varianceTable, pscdata_cat, pscdata, timeindex, newcodes)